use_frameworks!

platform :ios, '10.0'

target 'User_Example' do
  pod 'User', :path => '../'
  
  
  pod 'DataService', :path => '../../../zz_x_ai_packages/DataService/'
  pod 'XAIMediator', :path => '../../../zz_x_ai_packages/XAIMediator/'
  
  
  pod 'XAIPackagesLibs', :path => '../../../zz_x_ai_packages/'
  pod 'XAIModulesLibs', :path => '../../'
  
  
  # 通用依赖
  pod 'Bifrost', :path => '../../../zz_ios_packages/Bifrost/'

  target 'User_Tests' do
    inherit! :search_paths

    
  end
end
