use_frameworks!

platform :ios, '10.0'

target 'User_Example' do
  pod 'User', :path => '../'
  pod 'XAIModulesLibs', :path => '../../'

  target 'User_Tests' do
    inherit! :search_paths

    
  end
end
